add content to html and css
catharkriss/hw.css-box-model pull request #1
Opened 2024-06-21 17:54 UTC by catharkriss

коли додаю градуси у вигляді тегу span, то контейнер починає виходити за межи і підіймається вверх. як це можна пофіксити? спеціально залишила для прикладу; можливо, неправильно взагалі створила ці контейнери

2024-06-25 09:44 UTC, a1exalexander requested changes
Передивись ще раз відрізок уроку, де я робив це завдання! Має дуже тобі допомогти
обгортку зробила правильно! А все що всередині тега li треба ще обгорнути в теги

2024-06-28 16:42 UTC, catharkriss reviewed
додала зміни, сподіваюсь, що цього разу все краще

2024-07-11 13:19 UTC, a1exalexander approved these changes

2024-07-11 13:19 UTC, a1exalexander commented on index.html
> +            <h2 class="heading">CSS Weather Forecast <i class="wi wi-sunrise"></i></h2>
не можна пропускати рівні заголовків

2024-07-11 16:31 UTC, merged